### ISSUE TITLE
内容・仕様

### ISSUE THREAD

**Issue by keitakawamoto** [balloonbros/balanceball-android#1]
https://github.com/balloonbros/game/issues/1#issuecomment-52832462 より
## 1分間指定の位置に何秒キープできたかを競う

ただそれだけ。
Q:それならテーブルにスマートフォンを置けばいいのでは？
A:風を吹かせるので、手で上手くコントロールしないといけない。

![iphonegame](https://cloud.githubusercontent.com/assets/1661325/3987004/1d2175c4-28a1-11e4-886c-378a29b2932c.png)

クソゲーだが、それがいい。
## 予定
- 風の風速・方向はランダム
- 風が吹くのは3秒ほどで、１分の間に数回発生する
- 風が吹いたらその方向から落ち葉などが舞ってくる（視覚的に認識）
- 爽やかな風のSEを入れる
- 落ち葉などは固定アニメーション１個作って使い回す？
- 舞うスピードは風速に会わせてパターンを用意（速度を変えるだけ）
- １分経ったらスコア表示、ソーシャルへシェアできる
- 起動時のBBロゴは、このゲームのテイストVerにする
- aboutでBB紹介

**Comment by keitakawamoto** [comment]
## 作るもの以外で用意すべきもの
- SE

**Comment by tkengo** [comment]
ぎこちないけどなんとなく動くものはできたのであとで動画とってアップしよ。

**Comment by tkengo** [comment]
@keitakawamoto へ。

デモ動画
http://youtu.be/LdcKLZLd2z0

**Comment by keitakawamoto** [comment]
![LGTM](http://www.lgtm.in/p/WXjnfn3iq)

@tkengo 最高だ！！！！！！

**Comment by keitakawamoto** [comment]
### 得点ゾーンにいる間は視覚・聴覚でわかるアクションを起こす

> keita_kawamoto：ゲーム的に面白そうな要素を考えた
> keita_kawamoto：得点ゾーンにキープできている間、
> keita_kawamoto：０秒から１秒ごとに効果音を流す
> keita_kawamoto：チャリーンチャリーン
> keita_kawamoto：みたいな。
> keita_kawamoto：実際はチャリーンじゃない形になると思うけど
> keita_kawamoto：得点入ってる！！！上手く行ってる、って演出をさせると楽しい
> 
> tkengo：俺もさ、特典ゾーンにキープできてる時の演出かんがえてて
> tkengo：俺の場合はエフェクトで
> tkengo：得点ゾーンにいる間は白い枠が、たとえば赤くなって、ドクンドクンと鼓動する的な
> tkengo：今自分が得点ゾーンにいて、得点が加算されてるんだよ、っていうの視覚的にみせたい、と。
> 
> keita_kawamoto：いいね、視覚聴覚どっちもが楽しい

演出について考えておく。

**Comment by tkengo** [comment]
### 開始時にカウントダウンして0になった時点でゲームスタート

> keita_kawamoto : 開始まであと３秒
> keita_kawamoto : みたいなシーケンスもつけて。
> keita_kawamoto : 今スタートしたらいきなりボールががくっと落ちるしね。
> tkengo : > 開始まであと３秒
> tkengo : これはいるね。つけようと思ってた。

**Comment by keitakawamoto** [comment]
ボールが回ってる感じ欲しい。以下のような光沢あるボールにすれば、コロコロ、という音をつけるだけで、一枚の固定画像でありながら転がってるように見える。

![](http://mblog.maruhans.net/pc/uploads/images/blogset/data/file/1/4/0/1407/5124883/OiL8HHotiT-1373600455.jpg)

**Comment by keitakawamoto** [comment]
BGM作曲はまだ現実的ではないので、クラシックなどの著作権切れの楽曲を打ち込みで演奏し、それを利用する。
イメージはファミコンゲーム。ゲーム開始時にスタート表記と共にクラシックの一部が数秒流れる、という演出を多々見かけた。

> 開始時にカウントダウンして0になった時点でゲームスタート

このタイミングで流す。

**Comment by keitakawamoto** [comment]
@tkengo リザルト画面、ランキングなしの変わりに、`Twitterでツイート`ボタンを設置しよう。

**Comment by keitakawamoto** [comment]
### ゲームとしての面白さ部分の要素

前提：リリースまでの必須タスクではない

今後追加して行くと面白いかも？という要素。
- 得点エリアでキープしている間、１秒ごとにコインを稼げる。チャリーンという効果音はそれだけで楽しい。
- キープした秒数ではなく、一度に稼いだコイン数で競う。
- なぜならば人は💰が好きだから。秒を競うより、💰にしたほうが、喜びがある。
- そしてコインは蓄積できる。
- 1000コインで、背景を買える
- 消費コンテンツとしては、
  - 300コインで風の影響を受けない、あまり転がらない鉛玉化できる。
  - 500コインで、得点エリアで１秒おきではなくマシンガンのように連続コイン獲得ができる。とにかく爽快。
- 10秒連続キープするとコンボ扱いとし10コイン連続獲得（チャリリリリリリリーン）
- 20秒連続キープするとダブルコンボで20コイン連続獲得

など。

**Comment by keitakawamoto** [comment]
### ゲームとしての面白さ部分の要素2

前提：リリースまでの必須タスクではない

今後追加して行くと面白いかも？という要素その２。

@shoyan のアイデア。
- 得点エリアへのキープを邪魔するのは風だけではない、大砲の玉が横から飛んでくる。
- もちろん得点エリアと重なるようには放たれない。
- キープ中、ボールが転がって得点ゾーンからはなれてしまったときに、たまたま大砲の玉にあたってしまう、などにする。
- 大砲の玉にあたるとコインが10コイン散らばってしまい、得点から-10コインとなる。
- その際、ボールは勢いよく跳ね飛ばされる。
- 大砲の玉が飛んでくるポイントは予告される。ここから左へもうすぐ放たれる、という矢印を表示。

など。

**Comment by tkengo** [comment]
> 得点エリアでキープしている間、１秒ごとにコインを稼げる。チャリーンという効果音はそれだけで楽しい。
> キープした秒数ではなく、一度に稼いだコイン数で競う。
> なぜならば人は:moneybag:が好きだから。秒を競うより、:moneybag:にしたほうが、喜びがある。

この3行だけならそんなに大変じゃないし、良いエフェクトだと思うのでこっちデフォルトにしても良い気がした。

### さっき思いついたネタ

残り時間表示は単位が秒じゃなくて秒以下も表示するとものすごく早く時間が更新されていって焦りを演出できていいかも。

たとえばカンマ1桁を表示するとか。イメージ。
http://deadlinetimer.com/timer/2682

2桁でもいいかも。とにかく残り時間がどんどん減っていってるよ〜みたいに思わせれたら成功。

**Comment by keitakawamoto** [comment]
> 残り時間表示は単位が秒じゃなくて秒以下も表示するとものすごく早く時間が更新されていって焦りを演出できていいかも。

素晴らしい。カンマ２桁にしよう。

**Comment by keitakawamoto** [comment]
> この3行だけならそんなに大変じゃないし、良いエフェクトだと思うのでこっちデフォルトにしても良い気がした。

デフォルト確定！ :+1:

**Comment by keitakawamoto** [comment]
balanceball-android Freeze！ :snowflake:
