### ISSUE TITLE
ゲームクリエイターの先輩より

### ISSUE THREAD

**Issue by keitakawamoto** [balloonbros/balanceball-android#10]
@murasakipinko  にゲーム制作における凄く勉強になることをいろいろ教えてもらった。
- [Dr.Teeth](https://itunes.apple.com/jp/app/id516248176?cp)
- [ばいきんラボ](https://itunes.apple.com/jp/app/baikinrabo/id528225526)
- [ハナビショット！ -星空に花火を打ち上げるレトロドット絵ゲーム-](https://itunes.apple.com/jp/app/hanabishotto!/id556492322)

などを手がけるクリエイター。
## SE/BGMについて
- BGMはほぼ作ってる
- ツールはGarabeband
- 独自で学んだ
## ゲーム制作を始める時

Q. パズルの仕組みを作るのは、素人目線だと凄く複雑な仕組みのような気がする。
　実際のところ、どうなのか。ピンキリだとは思うけどアルゴリズム的な話になってそう。
　何は作れる、これはちょっと高度すぎる、みたいなのをできることなら把握したい。

A. 作れる作れないは最初は忘れたほうがいい。
　パズル・アクションなども最初考えることはあまりない。
　「これが作りたい！」っていうものがあって、それにジャンルがついてくる感じ。
　そこで制限かけるのもったいない。
　自分が作りたいものを作るべき。
## WEBともDTPとも大きく違う
- WEBともDTPとも比べて、とにかく奥が深い
- 見た目と音だけではない
- ルールもある
- レベルデザインもある
- ゲームのステージをデザインする人もいる
- 選任もいて、１つのゲームに対し職種は多岐にわたる
## まとめ

作りたいものを作っていけば、勉強になる。
自分で縛ることをしてはいけない。

**Comment by keitakawamoto** [comment]
バイブルにしよう。。。

**Comment by tkengo** [comment]
> 作りたいものを作っていけば、勉強になる。

まさにこれ

**Comment by keitakawamoto** [comment]
一つゲームを完成させたら閉じる

**Comment by murasakipinko** [comment]
私もまだまだ発展途上なのでｗゲームができたらみせてください。
楽しみにしてます！

**Comment by keitakawamoto** [comment]
:+1:

**Comment by keitakawamoto** [comment]
balanceball-android Freeze！ :snowflake:

**Comment by keitakawamoto** [comment]
ゲームに関する修行が必要。一旦凍結〜
