### ISSUE TITLE
途中でホームボタンを押しても一時停止状態になり、再起動扱いにしない

### ISSUE THREAD

**Issue by keitakawamoto** [balloonbros/balanceball-android#11]
ホーム画面へ戻ったあと、再度アイコンをタップしてゲームの続きをしようとしたらBBロゴからになる。途中の状態のまま、しばらくは維持しておきたい。

**Comment by tkengo** [comment]
自分の実機(DocomoのGalaxyS2のAndroid4.0)とエミュレーター上の端末(GalaxyS2のAndroid4.1)で試してみたけど、ホーム画面へ戻った後に再度アイコンをタップした場合はどちらともプレイ画面から再開した。

今度のハッカソンの時に @keitakawamoto のAndroidもってきて手元で確認させてほしい。

**Comment by keitakawamoto** [comment]
OK

**Comment by keitakawamoto** [comment]
@tkengo 

昨日状況を撮影して貼ろうと思ったら、

正常にプレイ画面から再開しました（ﾃﾍﾍﾟﾛ
