### ISSUE TITLE
Android 2.3.6でインストールが失敗する

### ISSUE THREAD

**Issue by shoyan** [balloonbros/balanceball-android#14]
@tkengo 
apkをインストールすると、「パッケージの解析に問題があります」というエラーがでて、インストールができない＞＜

**Comment by keitakawamoto** [comment]
うお

**Comment by tkengo** [comment]
バランスボールのサポートするバージョンがAndroid4系からなのでインストールできなかったと思われ。。。
2系でもインストールできるように調整してみます。

**Comment by shoyan** [comment]
あざますー！

**Comment by shoyan** [comment]
以下を参考にアンドロイドのアップデートを試みたものの、アップデートできず・・・
http://oshiete.goo.ne.jp/qa/7739912.html
https://www.nttdocomo.co.jp/binary/pdf/support/utilization/product_update/list/sc02c/SC-02C_software_pc.pdf

SC-03DはAndroid2までしか対応してないっぽい。
がくっ・・・

**Comment by tkengo** [comment]
@shoyan 2.3.6まで対応したapkを送ったのでインストール試してみてー！

**Comment by shoyan** [comment]
うおー！あざます！！！

**Comment by shoyan** [comment]
インストールできた:smile:

**Comment by tkengo** [comment]
:+1:
