### ISSUE TITLE
ゲーム中はディスプレイの省電力による自動電源オフを切る

### ISSUE THREAD

**Issue by tkengo** [balloonbros/balanceball-android#3]

**Comment by tkengo** [comment]
傾きを変えてるだけでしばらく画面に何も触れなかったら、画面が少し暗くなるってことか。
(edited)

keita_kawamoto [5:26 AM]
正解。この切り替わり時に凄く動きが鈍くなるのよね。処理してるからかな。

keita_kawamoto [5:26 AM]

> ディスプレイが消えるまではいかないってことなのかな。

keita_kawamoto [5:26 AM]
俺の方では消えたw

keita_kawamoto [5:26 AM]
最後までいった。

tkengo [5:26 AM] 
お、そうかｗ

keita_kawamoto [5:26 AM] 
w

tkengo [5:27 AM] 
段階的に暗くなっていって、それでも触れないと消えるんだね。

**Comment by tkengo** [comment]
http://android.keicode.com/basics/how-to-keep-screen-on.php

ここに書いてある方法でいけそう。

**Comment by tkengo** [comment]
上記リンクの方法は現在のAPIレベルでは非推奨になっているようなので、こっちを使う。

http://www.mihr.net/android/Mario_Zechner-5.html

```
Activity の getWindow() メソッドで Window オブジェクトを取得し
addFlags() メソッドで FLAG_KEEP_SCREEN_ON を指定する方法である
```

**Comment by tkengo** [comment]
実装完了。

**Comment by tkengo** [comment]
http://tiro105.hateblo.jp/entry/2014/07/05/192305

閉じたあとでアレだけど、こっちのほうが詳しかった。

**Comment by keitakawamoto** [comment]
まさかの補足w

**Comment by tkengo** [comment]
なんかもし後で見返した時に、不自由が無いようにと思ってｗ
実際 http://tiro105.hateblo.jp/entry/2014/07/05/192305 を見ながら実装したしね！

**Comment by keitakawamoto** [comment]
GJ
