### ISSUE TITLE
SEについて・完成の定義

### ISSUE THREAD

**Issue by keitakawamoto** [balloonbros/balanceball-android#4]
使用する効果音の候補について。

https://github.com/balloonbros/balanceball-android/issues/4#issuecomment-55716000 あたりから完成の定義に付いても議論。

**Comment by keitakawamoto** [comment]
システム音・電子音 http://www.kurage-kosho.info/system.html

この中から、balanceballのモックのイメージに近いもをいくつかチョイスした。
- http://www.kurage-kosho.info/mp3/button01.mp3
- http://www.kurage-kosho.info/mp3/button58.mp3
- http://www.kurage-kosho.info/mp3/button16.mp3
- http://www.kurage-kosho.info/mp3/one32.mp3

風のSEを優先して探し、あとはゲームのビジュアルを先に詰めた方が効率が良さそう。

**Comment by keitakawamoto** [comment]
効果音ラボ http://soundeffect-lab.info/sound/animal/

ここの `天気・自然現象` > `風が吹く1` を加工し短くしてフェードイン・フェードアウトすれば使えるかも。商用無料と書いてあるがライセンス要確認。

**Comment by keitakawamoto** [comment]
ひとまず風をみつけたので、残りの検索は優先度を下げる。
- [google検索：効果音　素材](https://www.google.co.jp/search?q=%E5%8A%B9%E6%9E%9C%E9%9F%B3%E3%80%80%E7%B4%A0%E6%9D%90&oq=%E5%8A%B9%E6%9E%9C%E9%9F%B3%E3%80%80%E7%B4%A0%E6%9D%90&aqs=chrome..69i57j0j69i65j0l3.3901j0j4&sourceid=chrome&espv=2&es_sm=119&ie=UTF-8#q=%E5%8A%B9%E6%9E%9C%E9%9F%B3%E3%80%80%E7%B4%A0%E6%9D%90&safe=off&start=10)
- [google検索：sound effects](https://www.google.co.jp/search?q=%E5%8A%B9%E6%9E%9C%E9%9F%B3%E3%80%80%E7%B4%A0%E6%9D%90&oq=%E5%8A%B9%E6%9E%9C%E9%9F%B3%E3%80%80%E7%B4%A0%E6%9D%90&aqs=chrome..69i57j0j69i65j0l3.3901j0j4&sourceid=chrome&espv=2&es_sm=119&ie=UTF-8#q=sound%20effects&safe=off)
- [【フリー素材】 これは使える！ ハイセンスな効果音・BGM素材まとめ](http://matome.naver.jp/odai/2134029515591779601)

**Comment by keitakawamoto** [comment]
## 音の扱いが致命的である

とにかく初心者。

素材をそのまま使うのもいいけど、やはり作成・編集スキルは欲しい。
GarabebandでSE・BGMを作成するゲームクリエイターの先輩がいたので、真似して作成してみる。
- [garageband bgm作成](https://www.google.co.jp/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8#q=garageband%20bgm%E4%BD%9C%E6%88%90)

**Comment by tkengo** [comment]
最初なので、あんまり意気込みすぎて全部自作ってのも大変だろうから、バランスボールでは感覚だけつかむって感じかな？

素材だとしてもまずは1個完成品を作ってみたいからね～ :+1:

**Comment by keitakawamoto** [comment]
そう、まずは試す。
風の音を用意したからSEはOK。
タイトルとリザルト、about以外はできたので、残りを仕上げて、ブラッシュアップのフローにはいったら音の学習もはじめる予定。

**Comment by keitakawamoto** [comment]
完成の定義に関して、ブラッシュアップは必須でない。

なので、完成までの必須タスク、俺の作業はあと少し。
という認識だよー @tkengo

**Comment by keitakawamoto** [comment]
しまった、木の葉のこと忘れてた。これも必須。gifアニメを用意。

**Comment by tkengo** [comment]
ゲームの場合はgifアニメじゃなくてcssスプライトのような感じで、各コマ画像を1つの画像をまとめて1つのファイルにしてほしい！

**Comment by tkengo** [comment]
> 完成の定義に関して、ブラッシュアップは必須でない。

ストアに申請して遊べるところまでもっていくのが完成だと思ってたので、俺とは認識のズレあり？
この辺ずれてると今後やりにくそうだから、今のうちにどちらかの認識に合わせておこう。

**Comment by keitakawamoto** [comment]
issueに書き出し万歳。
合わせてこう！

こちらの認識としては

#### 基本
- 起動して、プレイできる。ほぼ落ちない。ランキングに掲載される。
- すべての画面が揃っている（起動・タイトル・プレイ・リザルト・ランキング・About）
- 途中で画面が消灯したり画面回転しない
- 装飾・テイスト関連は最低限のレベルで用意する

#### プレイ部分
- リアルな動きでボールを転がせる
- 得点部分にあると得点が入る
- 風が吹いたら正しく影響を受ける
- 風に関するエフェクト（木の葉）がある
- 秒数が表示される
- 得点が表示される

#### 公開
- ストア申請
- 申請が通る
- ダウンロードして遊べる

以上が俺の認識だよー。

> 装飾・テイスト関連は最低限のレベルで用意する

これに関しては、まずすべてを揃える事に重きを置く、という意味。
用意すれば最低限の「完成」扱いであり、その後時間的制約が来るまでとことんブラッシュアップする。
完成扱いって言うのは、「時間をかけすぎても〜」っていうのを心配かけないようにするため。
もちろん、 @tkengo がバッチリなクオリティになるまでとことん詰めた方がいいと思うならば、俺は時間をかけてとことんやるよ:sunglasses:

**Comment by tkengo** [comment]
今完全に認識があいました。ありがとう。

> こちらの認識としては

問題なし！！

**Comment by keitakawamoto** [comment]
:+1:

**Comment by keitakawamoto** [comment]
音に関しては https://github.com/balloonbros/balanceball-android/issues/12 に統一する。
