### ISSUE TITLE
起動からの画面類と遷移・世界観

### ISSUE THREAD

**Issue by keitakawamoto** [balloonbros/balanceball-android#5]
全体の流れとその際の画面のビジュアルについて。
※共有を兼ねてハッカソン毎の進捗を記録する。

**Comment by keitakawamoto** [comment]
激しくプロトタイプ。

起動
![balanceball _03](https://cloud.githubusercontent.com/assets/1661325/4257634/180be268-3ac6-11e4-9146-4d2740611496.png)

タイトル
![balanceball _05](https://cloud.githubusercontent.com/assets/1661325/4257642/2d7d72a6-3ac6-11e4-9d67-f914c19a1e14.png)

プレイ
![balanceball _09](https://cloud.githubusercontent.com/assets/1661325/4257677/8bc5d880-3ac6-11e4-8ac5-d5aae5a80918.png)

リザルト
![balanceball _10](https://cloud.githubusercontent.com/assets/1661325/4257650/3fb2cf34-3ac6-11e4-94bf-98ee13ea4566.png)

**Comment by tkengo** [comment]
テンションあげあげまっく

**Comment by keitakawamoto** [comment]
## 気付き
- まず世界観を作らなければ、タイトル画像もテイストも定まらない
- https://github.com/balloonbros/balanceball-android/issues/1#issuecomment-56610443 にて光沢がある玉にすれば静止画でも回転している感が出ると書いたが、フラットデザインでも可能。

![image](https://cloud.githubusercontent.com/assets/1661325/4404573/9f04f7b4-44b2-11e4-9c30-4686a6baf96b.png)
- ゲームとWEBは違うが、デザインテイストはWEBのものが通用する。フラットデザインをフル活用する。

**Comment by keitakawamoto** [comment]
#### リザルト経過
- ソーシャルシェア追加
- ボタン類をわかりやすく

![image](https://cloud.githubusercontent.com/assets/1661325/4405120/f4cbd0fa-44b7-11e4-8373-4caa2da3a28d.png)

**Comment by keitakawamoto** [comment]
## Todo
- [ ] 得点時の演出
- [ ] タイトル
- [ ] プレイ開始までのカウントダウン画面

**Comment by keitakawamoto** [comment]
風速表記は`m/s`のほうがいいか？

**Comment by tkengo** [comment]
> 風速表記はm/sのほうがいいか？

ソッチのほうが、それっぽくていいかも！

**Comment by keitakawamoto** [comment]
よし、ではそうしよう！

**Comment by keitakawamoto** [comment]
画面いっぱいの画像を用意する場合、`1920*1080`が理想サイズとのこと

**Comment by keitakawamoto** [comment]
@tkengo 

![image](https://cloud.githubusercontent.com/assets/1661325/5027302/8e5faaa0-6b70-11e4-83c2-1fe364ea363d.png)
- 左上 `#ff6846`
- 中央 `#fd5341`
- 右下 `#eb2e48`

:point_down: ※白いから見えないけどあります
![bb](https://cloud.githubusercontent.com/assets/1661325/5027389/bcaeb97c-6b71-11e4-9dcc-fcbfd9074551.png)
:point_up:

**Comment by keitakawamoto** [comment]
balanceball-android Freeze！ :snowflake:
