### ISSUE TITLE
傾きによるボールの動きを調整するスレ

### ISSUE THREAD

**Issue by tkengo** [balloonbros/balanceball-android#7]
バランスボールの肝なので違和感のないものにしていく。

**Comment by tkengo** [comment]
1. +の傾きから-の傾き(その逆もしかり)にした場合の減速度合いを高めた
2. 止まってる間は少しの傾きで少し動くようにした
3. 動いている時に傾き3度以内だと徐々に減速してストップするようにした

3は要するに完全に水平じゃなくっても、「ほぼ」水平だったらボールの動きが止まる。

という風に調整。

**Comment by tkengo** [comment]
ボールが止まってる時の動きがまだぎこちないのでそこを微調整する。

**Comment by tkengo** [comment]
以下の調整を加えた。
- よりダイナミックに大きく傾けてボールを動かさないといけないようにした（※いままでは少々の傾きでボールが転がりすぎていた）
- ただし、動き始めだけは少しの傾きでも転がり始めるように調整

**Comment by keitakawamoto** [comment]
いいよいいよーリアルになって行ってる。
物理演算最高！（これも物理演算と呼んでええのよね）

**Comment by tkengo** [comment]
ボールの動きはいい感じになったと思うので閉じ。また調整が必要になったら別途たてる。
