### ISSUE TITLE
シーン管理導入

### ISSUE THREAD

**Issue by tkengo** [balloonbros/balanceball-android#8]
バランスボールには以下の4つのシーンを用意する予定。
- 起動シーン
- タイトルシーン
- プレイシーン
- リザルトシーン

各シーン間の遷移ができるようにタスクシステムを作りこむ。

**Comment by keitakawamoto** [comment]
ランキング・Aboutも！

**Comment by tkengo** [comment]
イエッサー

**Comment by tkengo** [comment]
今気付いたが、ランキング機能を実装するためにはユーザーを識別するための何かしらの認証とサーバー側のランキング実装が必要になりそう。ランキングは話がでかくなるな。

**Comment by keitakawamoto** [comment]
まずはいらんか。
練習という名目もあるし。

**Comment by tkengo** [comment]
そうだね。まずはミニマムでいこう。

**Comment by keitakawamoto** [comment]
異議なし:bulb:

**Comment by tkengo** [comment]
各シーンはこれから作りこむけど、シーン管理のシステムはできたので閉じます。
