### ISSUE TITLE
木の葉について

### ISSUE THREAD

**Issue by keitakawamoto** [balloonbros/balanceball-android#9]
`風が吹いている` ということをわかりやすく視認させる目的で挿入する。

https://github.com/balloonbros/balanceball-android/issues/4

> ゲームの場合はgifアニメじゃなくてcssスプライトのような感じで、各コマ画像を1つの画像をまとめて1つのファイルにしてほしい！

木の葉をどうやって実装するかを検討する。

**Comment by keitakawamoto** [comment]
@tkengo 、その理由とは？

**Comment by tkengo** [comment]
基本的にゲームというのは
- フレームと呼ばれる単位で処理/描画を繰り返す
- ゲームやってると **FPS** とか聞いたことあるかもだけど1秒間に何回の処理/描画をするかという単位がある
- PCやAndroidだと一般的なゲームのFPSは60。要は1秒間に60回の処理/描画を実行する。(バランスボールのFPSも60)
- そのフレームの中でたとえば
  1. 1px右に動かす
  2. アニメーションを1コマ進める
  3. 描画する
- てな感じでパラパラ漫画のような要領で、少しずつ位置やコマを動かしては描画して、を繰り返す

ので、最初からgifアニメだとフレーム処理と相性が悪い。

**Comment by keitakawamoto** [comment]
なるほど。webとは決定的に違うね。勉強になる。
ゲーム作成においてアニメーションはどうやって作ればいいかな？
ポピュラーな作り方を検索してみるか。

たとえば、[OPTPiX SpriteStudio](http://www.webtech.co.jp/spritestudio/for_android.html)とかか、なるほど。

**Comment by tkengo** [comment]
RPGに出てくるキャラとかはたとえばこういう風に1枚画像になってるねー。
![](http://blog-imgs-38.fc2.com/o/n/b/onbird/tor_main.png)

gifアニメを想定してたんだったら、とりあえずgifアニメ用の画像を数枚用意するように考えてたと思うので、それを縦なり横なりに連結して1枚の画像にすれば大丈夫そう。

**Comment by keitakawamoto** [comment]
（@tkengo ...詳しい...）

画像の配置は了解！
用意した後は、どんなツールを使ってアニメーション化させればいいのかな？

**Comment by tkengo** [comment]
> どんなツールを使ってアニメーション化させればいいのかな？

これは自分の確認用に、ってこと？であれば用意した画像を連結して確認用のgifアニメを作ってみるとか、画像を同じフォルダにおいてプレビューアプリで自分で右キー連打してアニメーションっぽくしてみるとか、くらいで大丈夫そう。

もしけーたくんが用意した画像をゲームで使るようにするために「アニメーション化」という別途作業が必要なのか、と考えているのであればそれは必要ないよ :hamster: 各コマの画像が配置されている1枚画像があれば、あとはアプリ側で制御するから。

**Comment by keitakawamoto** [comment]
> もしけーたくんが用意した画像をゲームで使るようにするために「アニメーション化」という別途作業が必要なのか、と考えているのであればそれは必要ないよ :hamster: 各コマの画像が配置されている1枚画像があれば、あとはアプリ側で制御するから。

わかりやすい...

了解した！確認はgifアニメで行うとするね。
俺web脳だな完全に。ゲーム脳化も進めたい。

アプリ側制御では俺も参加します！

**Comment by keitakawamoto** [comment]
https://github.com/balloonbros/balanceball-android/issues/12 に結合する。
